### ISSUE TITLE
Button with Over & Pressed states

### ISSUE THREAD

**Issue by NemoStein** [orange-games/phaser-nineslice#2]
Consider the following spriteseet: 

![image](https://cloud.githubusercontent.com/assets/2738812/22905335/0b5785f2-f227-11e6-8f82-7f424ef20a8d.png)

Is it possible to create a 9sliced button with over and pressed states from this kind of asset?

**Comment by AleBles** [comment]
Usually button's that are ninesliceable also require stuff like text or icon's in them, for which a default Phaser.Button has no support. So I usually end up constructing my own buttons.

**Comment by NemoStein** [comment]
That was exactly what I thought... Thanks for your feedback.
