### ISSUE TITLE
Error in README 'load the plugin'

### ISSUE THREAD

**Issue by brunoimbrizi** [orange-games/phaser-nineslice#3]
Current README says:
```
function preload(){
game.plugins.add(PhaserNineSlice.NineSlice);
}
```

Which outputs an error to the console:
`Uncaught TypeError: game.cache.getNineSlice is not a function`

The correct way of adding the plugin can be seen in the example:

```
game.plugins.add(PhaserNineSlice.Plugin);
```

**Comment by AleBles** [comment]
yes, well spotted. Thank you!
